### ISSUE TITLE
Shuttle windows are too easy to dismantle

### ISSUE THREAD

**Issue by Philamore** [DeltaV-Station/Delta-v#1518]
## Description

Shuttle windows have the same deconstruction steps as regular windows, being screwdriver then wrench.
**Reproduction**

Go to any shuttle window to include the evac shuttle, use a screwdriver, then a wrench, and you will have a hole where the window was and only 2 ordinary glass sheets.

**Screenshots**

**Additional context**

Keep in mind that anyone can just deconstruct the evac shuttle windows with a wrench and screwdriver, that is a bit too easy to space the shuttle.

**Comment by IamVelcroboy** [comment]
These are the steps for shuttle windows. Or at least they should be. Unless something's broken
```yml
    - node: shuttleWindow
      entity: ShuttleWindow
      edges:
        - to: start
          completed:
            - !type:SpawnPrototype
              prototype: SheetRGlass1
              amount: 2
            - !type:SpawnPrototype
              prototype: SheetPlasteel1
              amount: 2
            - !type:DeleteEntity {}
          steps:
            - tool: Welding
              doAfter: 6
            - tool: Screwing
              doAfter: 2
            - tool: Prying
              doAfter: 3
            - tool: Welding
              doAfter: 5
            - tool: Screwing
              doAfter: 1
            - tool: Prying
              doAfter: 2
            - tool: Welding
              doAfter: 4
            - tool: Anchoring
              doAfter: 1
```
