### ISSUE TITLE
job requirements should be moved from job prototypes

### ISSUE THREAD

**Issue by MilonPL** [DeltaV-Station/Delta-v#1973]
## Description

Job requirements should be moved away from JobPrototypes and synced with upstream (less conflicts, yippee) into the JobRequirementOverridePrototype. Sounds hard but it's actually all yaml, so it's a good first issue. 
Basically you need to create a new `requirement_overrides.yml` in the DeltaV namespace and then update the `deltav.toml` file to include `role_timer_override = DeltaV` under `[game]`

Example:
```yaml
- type: jobRequirementOverride
  id: DeltaV
  jobs:
    HeadOfSecurity:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 72000 # 20 hours
    - !type:RoleTimeRequirement
      role: JobWarden
      time: 36000 # 10 hours
    - !type:DepartmentTimeRequirement 
      department: Command
      time: 36000 # 10 hours
    - !type:OverallPlaytimeRequirement
      time: 90000 # 25 hours
```
